import type { ProviderAccountDiagnostic, ProviderLoginChallenge } from "./control.ts";

const escape = (value: string | number) => String(value).replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const routeNames = { "claude-api": "Claude API", "claude-code": "Claude Code", codex: "Codex" };
const accountStates = { unchecked: "Account not checked", "signed-out": "Signed out", "signing-in": "Waiting for sign-in", "signed-in": "Signed in", unavailable: "Account needs attention", "recovery-required": "Recovery required", closed: "Account controller closed" };

/** Sign-in challenges are view memory only; never write them to storage or activity. */
export function renderProviderAccounts(accounts: readonly ProviderAccountDiagnostic[] | undefined, editable: boolean,
  challenges: ReadonlyMap<string, ProviderLoginChallenge>): string {
  return `<section class="section"><h2>Agent accounts</h2><p class="section-description">Choose an account for each contact in Behavior. Connect your Codex account with ChatGPT. Claude API uses separate API billing.</p><div class="capability-list">${accounts?.length ? accounts.map(account => {
    const native = account.managedAccount;
    const observedChallenge = challenges.get(account.id);
    const challenge = observedChallenge?.loginId === native?.pendingLoginId ? observedChallenge : undefined;
    const canManage = editable && native?.state !== "closed" && native?.state !== "recovery-required";
    const controls = native ? `<p>${accountStates[native.state]}${native.state === "signed-in" ? ` · ${native.modelCount} models discovered` : ""}</p><div class="form-actions"><button class="button" data-provider-check="${escape(account.id)}" ${!canManage ? "disabled" : ""}>Check account</button>${native.state !== "signed-in" && native.state !== "signing-in" ? `<button class="button" data-provider-login="${escape(account.id)}" ${!canManage ? "disabled" : ""}>Sign in with ChatGPT</button>` : ""}${native.pendingLoginId ? `<button class="button" data-provider-cancel="${escape(account.id)}" ${!canManage ? "disabled" : ""}>Cancel sign-in</button>` : ""}${native.state === "signed-in" || native.state === "signing-in" || native.state === "unavailable" ? `<button class="button" data-provider-logout="${escape(account.id)}" ${!canManage ? "disabled" : ""}>Sign out</button>` : ""}</div>`
      : account.route === "claude-api" ? `<button class="button" data-provider-check="${escape(account.id)}" ${!editable ? "disabled" : ""}>Check account</button>` : "";
    const login = native?.state === "signing-in" && challenge ? `<div class="provider-login"><p>Copy this address into your browser${challenge.type === "chatgptDeviceCode" ? ", then enter the code below" : " to sign in"}. Return here and check the account when you finish.</p><label for="signin-address-${escape(account.id)}">Sign-in address</label><input id="signin-address-${escape(account.id)}" type="text" readonly spellcheck="false" autocomplete="off" value="${escape(challenge.type === "chatgptDeviceCode" ? challenge.verificationUrl : challenge.authUrl)}">${challenge.type === "chatgptDeviceCode" ? `<label for="signin-code-${escape(account.id)}">One-time code</label><input id="signin-code-${escape(account.id)}" type="text" readonly spellcheck="false" autocomplete="off" value="${escape(challenge.userCode)}">` : ""}</div>` : "";
    return `<div class="capability-row"><div><strong>${escape(account.label)} · ${routeNames[account.route]}</strong><p>${escape(account.detail)}</p>${account.status === "ready" ? `<p>Replies: ${escape(account.defaultReplyModel ?? "Unavailable")}<br>Classifier: ${escape(account.classifierModel ?? "Unavailable")}</p>` : ""}${controls}${login}</div><span class="capability-state ${account.status === "ready" ? "available" : account.status === "unavailable" ? "unsupported" : "setup-required"}">${native ? "Replies unavailable" : account.status === "ready" ? "Ready" : account.status === "unavailable" ? "Unavailable" : "Setup required"}</span></div>`;
  }).join("") : `<p class="quiet-note">Configured accounts appear here when the daemon is connected.</p>`}</div><p class="quiet-note">Account checks send no message or paid prompt. Signing in does not enable replies. Credentials stay in private host storage.</p></section>`;
}
