import {
  absoluteUrl,
  AGENT_CLI_URL,
  AGENT_SETUP_PROMPT,
  ARCHITECTURE_URL,
  GETTING_STARTED_URL,
  GHOSTGET_SETUP_URL,
  GITHUB_URL,
  MESSAGING_APPS_URL,
  REPLY_CREDITS_NOTE,
  REPLY_WRITERS_PRECEDENCE,
  REPLY_WRITERS_SENTENCE,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_STATUS,
  SITE_WHAT_IT_IS,
  SUBSCRIPTION_GUIDE_URL,
  XCB_URL,
} from '../_lib/site';
import { MESSAGING_APPS, REPLY_WRITERS } from '../_lib/landing';
import { blogPostPath, indexableBlogPosts } from '../_lib/blog';

export function GET() {
  const body = [
    `# ${SITE_NAME}`,
    '',
    SITE_DESCRIPTION,
    '',
    `${SITE_WHAT_IT_IS} It is a headless macOS command line and background service with no window or menu bar icon, and a coding agent such as Claude Code, Codex, or Devin can set it up by following the written guide.`,
    '',
    'The website is informational. It never receives private message history, contacts, profiles, or drafts.',
    '',
    '## Current Textbutler development status',
    SITE_STATUS,
    '',
    '## How it works',
    'Someone writes in a one-to-one chat you turned on. Ghostget, a separate Mac tool you install first, passes the message to Textbutler in the background. Textbutler checks that the person is turned on, the chat is one-to-one, the message says “butler” (any capitalization, whole word), it has been at least 5 minutes since you last wrote in the chat, and the person has had fewer than 12 replies this hour. It waits 8 seconds so a burst of texts gets one answer, then sends 🤖{ 👀 } as an ordinary marked text message. It reads the notes you keep for that person and the recent conversation (in the owner’s own chat it can also search the full chat history; for other people that is off unless the owner enables it), and your chosen model writes the reply. The reply is sent wrapped as 🤖{ … }. A send with an unknown outcome is never repeated. Smart mode replies only when the model is at least 85% sure and otherwise stays silent. The owner can say “butler” in any turned-on chat, including their own, to ask it something. Group chats, reactions, old messages, SMS, and RCS are ignored.',
    '',
    '## Messaging apps',
    ...MESSAGING_APPS.map((app) => `- ${app.name}${app.networks === undefined ? '' : ` (${app.networks})`}: ${app.chip}. ${app.gets} ${app.limits}`),
    `Ghostget setup: ${GHOSTGET_SETUP_URL}`,
    '',
    '## What writes replies',
    REPLY_WRITERS_SENTENCE,
    ...REPLY_WRITERS.map((writer) => `- ${writer.name}: ${writer.chip}. Command: ${writer.command.replaceAll('\n', ' then ')}. What leaves your Mac: ${writer.leaves} ${writer.note}`),
    REPLY_CREDITS_NOTE,
    REPLY_WRITERS_PRECEDENCE,
    `AI replies come only from the local install that bun run textbutler:install builds; it checks its own source against the last reviewed version first. Running from source never writes AI replies. A subscription account must also pass providers check, and the model gets no tools of its own through xcb (${XCB_URL}). With no Gateway key saved, a local Ollama server that already serves qwen3:4b-instruct-2507-q4_K_M is detected automatically when the background service starts; textbutler providers local chooses it explicitly (stop the service first). The Claude API route is not available in any build of this repository.`,
    '',
    '## Setup with a coding agent',
    'There is no one-line installer, no app to download and no published Textbutler package, and no Textbutler setup skill yet. Setup builds a small helper app on the Mac so macOS can grant iMessage access; it has no window. A person must turn on Full Disk Access, allow the Messages prompt when setup re-runs, pair WhatsApp or Beeper, and paste a key or sign in. Paste this prompt into Claude Code, Codex, or Devin:',
    '',
    '```text',
    AGENT_SETUP_PROMPT,
    '```',
    '',
    'Manual path: bun install --frozen-lockfile --ignore-scripts && bun run textbutler tui.',
    '',
    '## Safety defaults',
    'New installations start paused and new contacts start disabled. Setup, contact selection, and history import never send a message. Every butler message, including the 👀, is wrapped in 🤖{ }; the marker can be removed per contact but never in your own chat. textbutler pause stops everything; textbutler contacts disable turns one person off. Drafts: replies suggest CONTACT, replies show DRAFT, then replies send DRAFT DIGEST with the exact review digest; drafts expire after 15 minutes. A submitted result means the messaging app accepted the message, not that it was delivered. Web search runs only when a Gateway key is saved; then it is available for turned-on people (in your own chat, only when you ask), uses that key even when a local model writes replies, and refuses queries that reuse words from private messages. The owner can turn search off for one person from the command line. Optional learning is off by default and needs a Claude Code subscription through xcb; when on, it can keep up to 64 sourced notes per chat, which the owner can list and clear from the command line. Gateway spending stops at $1 a day. Test inference and delivery on your own account before relying on them.',
    '',
    `Guided setup: ${GETTING_STARTED_URL}`,
    `Messaging app support and live limitations: ${MESSAGING_APPS_URL}`,
    `Subscriptions through xcb: ${SUBSCRIPTION_GUIDE_URL}`,
    `Agent JSON CLI: ${AGENT_CLI_URL}`,
    `Architecture: ${ARCHITECTURE_URL}`,
    '',
    '## Legacy Message Like Me history tools',
    'The following catalog describes the published Message Like Me history reader and its checked historical producer versions. It is not a Textbutler live transport support matrix. Installing the legacy package does not install Textbutler or enable automatic replies.',
    'Beeper via Ghostget lets users bring a finished private bundle into the same local evidence corpus as other sources. Ghostget v0.17.1 adapter beeper-local v2.4.0 owns 32 reviewed Beeper operations: 26 run through one pinned Beeper CLI 0.6.2 executable, including supported actions and writes, plus six fixed Desktop loopback reads. The executable’s reported 0.6.2 is runtime authority; the upstream tagged packages/cli/package.json declaration of 0.6.1 is provenance only. Message Like Me receives no provider credentials, never calls Ghostget or Beeper operations, and never sends; it does not claim complete history.',
    'Supported sources are Apple Messages; X data archive DMs, not X Chat; the finished Beeper bundle from Ghostget’s internal bounded v1 export; native WhatsApp via Ghostget and official Wacli through a one-account v2 bundle; and macOS Contacts for optional label enrichment. Every ingest path is read-only with respect to its source. Message Like Me does not invoke provider operations or access a network.',
    'The Ghostget v0.17.1 and Wacli v0.15.0 WhatsApp producer omits reaction-shaped rows with reaction-state-unproven because current active or removed state cannot be proved. An empty reaction artifact is unobservable reaction behavior, not evidence that no reactions occurred.',
    '',
    '## Optional development support',
    'Textbutler offers optional paid development support and no newsletter. `messagelikeme support` and `textbutler support` show the current options; agents follow `support protocol --json` for the closeout flow, and `HRANESS_SUPPORT=off` turns incidental notices off.',
    '',
    '## Canonical pages',
    `- ${absoluteUrl('/')}`,
    `- ${absoluteUrl('/sources')}`,
    `- ${absoluteUrl('/docs')}`,
    `- ${absoluteUrl('/methodology')}`,
    `- ${absoluteUrl('/research')}`,
    `- ${absoluteUrl('/about')}`,
    `- ${absoluteUrl('/compare/ghostreply')}`,
    '',
    '## Blog',
    `- ${absoluteUrl('/blog')}`,
    ...indexableBlogPosts().map((post) => `- [${post.title}](${absoluteUrl(blogPostPath(post))}): ${post.dek}`),
    '',
    '## Source',
    `- ${GITHUB_URL}`,
    '',
  ].join('\n');

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
