import {
  absoluteUrl,
  AGENT_CLI_URL,
  AGENT_SETUP_PROMPT,
  ARCHITECTURE_URL,
  GETTING_STARTED_URL,
  GHOSTGET_SETUP_URL,
  GITHUB_URL,
  MESSAGING_APPS_URL,
  REPLY_WRITERS_PRECEDENCE,
  REPLY_WRITERS_SENTENCE,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_STATUS,
  SITE_WHAT_IT_IS,
  SUBSCRIPTION_GUIDE_URL,
  XCB_URL,
} from '../_lib/site';
import { MESSAGING_APPS, REPLY_WRITERS } from '../_lib/landing';
import { blogPostPath, indexableBlogPosts } from '../_lib/blog';
import { isIndexableComparison } from '../compare/_lib/comparison-admissions';
import { COMPARISONS_CHECKED_ON, HUB_ENTRIES, HUB_FRAMING, HUB_PAGE_ENTRIES } from '../compare/_lib/comparisons';

const COMPARISON_PATHS = HUB_PAGE_ENTRIES.map(({ path }) => path).filter(isIndexableComparison);

export function GET() {
  const body = [
    `# ${SITE_NAME}`,
    '',
    SITE_DESCRIPTION,
    '',
    `${SITE_WHAT_IT_IS} It is a macOS command line and background service with no window or menu bar icon. A coding agent such as Claude Code, Codex, or Devin can set it up by following the setup guide.`,
    '',
    'This website is informational. It never receives your messages, contacts, notes, or drafts.',
    '',
    '## Key facts',
    '- Platform: macOS only. The Mac must stay awake and signed in. There is no iPhone, Windows, or Linux version.',
    '- Price and license: free and open source under the MIT license.',
    '- Messaging apps: iMessage, WhatsApp, and Beeper, connected through GhostGet.',
    '- Where it answers: only in the direct and group conversations you turn on, from your own account.',
    '- Default trigger: messages that contain the word “butler”; Smart mode is optional.',
    '- Disclosure: replies are wrapped in 🤖{ } by default; the marker is configurable per conversation.',
    '- Memory: editable notes for each conversation, stored as ordinary files on your Mac.',
    `- Reply writers: ${REPLY_WRITERS_SENTENCE}`,
    `- Source: ${GITHUB_URL}`,
    '',
    '## How TextButler compares',
    HUB_FRAMING,
    `Comparisons checked on ${COMPARISONS_CHECKED_ON} against each product’s public pages: ${absoluteUrl('/compare')}`,
    ...HUB_ENTRIES.map(({ hubLine, name, path }) => `- [TextButler compared with ${name}](${absoluteUrl(path !== undefined && isIndexableComparison(path) ? path : '/compare')}): ${hubLine}`),
    '',
    '## Before you start',
    SITE_STATUS,
    '',
    '## How it works',
    'GhostGet connects TextButler to the messaging apps on your Mac. Before answering, TextButler checks that the conversation is turned on, that the message fits the reply mode, how recently you wrote, and the reply limits. Keyword mode waits for “butler” as a whole word, in any capitalization. Smart mode can recognize a request for help without the keyword and stays silent when unsure. TextButler reads the conversation’s notes and recent messages, then asks your chosen model to write a reply. Replies and acknowledgments carry an AI marker by default. You can change the marker per conversation, but it always stays visible in your own chat. If TextButler can’t tell whether a send went through, it doesn’t send it again.',
    '',
    '## Messaging apps',
    ...MESSAGING_APPS.map((app) => `- ${app.name}${app.networks === undefined ? '' : ` (${app.networks})`}: ${app.gets} ${app.limits}`),
    `GhostGet setup: ${GHOSTGET_SETUP_URL}`,
    '',
    '## What writes replies',
    REPLY_WRITERS_SENTENCE,
    ...REPLY_WRITERS.map((writer) => `- ${writer.name}: ${writer.note} ${writer.leaves} Command: ${writer.command.replaceAll('\n', ' then ')}.`),
    REPLY_WRITERS_PRECEDENCE,
    `Automatic AI replies need the installed TextButler command; the setup guide covers installation and account checks. xcb connects an AI subscription without giving the reply model command access to your Mac: ${XCB_URL}.`,
    '',
    '## Set up with a coding agent',
    'Your coding agent can install TextButler, connect your messaging apps, and check the setup. You grant macOS access, pair accounts, and choose who may receive replies. Paste this prompt into Claude Code, Codex, or Devin:',
    '',
    '```text',
    AGENT_SETUP_PROMPT,
    '```',
    '',
    `Manual setup: ${GETTING_STARTED_URL}`,
    '',
    '## Safety defaults',
    'New installations start paused and new conversations start turned off. Setup, contact selection, and history import never send a message. `textbutler pause` stops all automatic replies; `textbutler contacts disable` turns one conversation off. To review a reply before it goes out, run `textbutler replies suggest CONTACT`, `textbutler replies show DRAFT`, then `textbutler replies send DRAFT DIGEST`. Drafts expire after 15 minutes. Optional web search sends queries through a saved Gateway key, even when a local model writes the reply, and each conversation’s settings control whether search is available. Optional learning starts off and requires a Claude Code subscription through xcb; you can review or clear what it remembers. Gateway spending stops at $1 a day.',
    '',
    '## Guides',
    `- Setup guide: ${GETTING_STARTED_URL}`,
    `- Messaging apps and their limits: ${MESSAGING_APPS_URL}`,
    `- AI subscriptions through xcb: ${SUBSCRIPTION_GUIDE_URL}`,
    `- Agent JSON CLI: ${AGENT_CLI_URL}`,
    `- Architecture: ${ARCHITECTURE_URL}`,
    '',
    '## Optional development support',
    'TextButler offers optional paid development support and no newsletter. `textbutler support` shows the current options; agents follow `support protocol --json` for the closeout flow, and `HRANESS_SUPPORT=off` turns incidental notices off.',
    '',
    '## Pages',
    `- ${absoluteUrl('/')}`,
    `- ${absoluteUrl('/docs')}`,
    `- ${absoluteUrl('/about')}`,
    `- ${absoluteUrl('/compare')}`,
    ...COMPARISON_PATHS.map((path) => `- ${absoluteUrl(path)}`),
    '',
    '## Blog',
    `- ${absoluteUrl('/blog')}`,
    ...indexableBlogPosts().map((post) => `- [${post.title}](${absoluteUrl(blogPostPath(post))}): ${post.dek}`),
    '',
    '## Source',
    `- ${GITHUB_URL}`,
    '',
  ].join('\n');

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
