import {
  absoluteUrl,
  AGENT_CLI_URL,
  AGENT_SETUP_PROMPT,
  ARCHITECTURE_URL,
  GETTING_STARTED_URL,
  GHOSTGET_SETUP_URL,
  GITHUB_URL,
  MESSAGING_APPS_URL,
  REPLY_WRITERS_PRECEDENCE,
  REPLY_WRITERS_SENTENCE,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_STATUS,
  SITE_WHAT_IT_IS,
  SUBSCRIPTION_GUIDE_URL,
  XCB_URL,
} from '../_lib/site';
import { MESSAGING_APPS, REPLY_WRITERS } from '../_lib/landing';
import { blogPostPath, indexableBlogPosts } from '../_lib/blog';

export function GET() {
  const body = [
    `# ${SITE_NAME}`,
    '',
    SITE_DESCRIPTION,
    '',
    `${SITE_WHAT_IT_IS} It is a headless macOS command line and background service with no window or menu bar icon, and a coding agent such as Claude Code, Codex, or Devin can set it up by following the written guide.`,
    '',
    'The website is informational. It never receives private message history, contacts, profiles, or drafts.',
    '',
    '## Start with a conversation',
    SITE_STATUS,
    '',
    '## How it works',
    'GhostGet connects TextButler to the messaging apps on your Mac. TextButler checks the selected conversation, reply mode, recent activity from you, and reply limits before answering. Keyword mode waits for “butler” as a whole word, in any capitalization. Smart mode can recognize a request for help without the keyword and stays silent when the result is uncertain. It reads the contact’s notes and recent messages, then asks your chosen model to write a reply. Replies and acknowledgments carry an AI marker by default; you can configure it per person. The marker stays visible in your own chat. If a send has an unknown outcome, TextButler does not repeat it.',
    '',
    '## Messaging apps',
    ...MESSAGING_APPS.map((app) => `- ${app.name}${app.networks === undefined ? '' : ` (${app.networks})`}: ${app.gets} ${app.limits}`),
    `GhostGet setup: ${GHOSTGET_SETUP_URL}`,
    '',
    '## What writes replies',
    REPLY_WRITERS_SENTENCE,
    ...REPLY_WRITERS.map((writer) => `- ${writer.name}: ${writer.note} ${writer.leaves} Command: ${writer.command.replaceAll('\n', ' then ')}.`),
    REPLY_WRITERS_PRECEDENCE,
    `Use the installed TextButler command for automatic replies. The setup guide covers installation and account checks. xcb connects an AI subscription without giving the reply model command access to your Mac: ${XCB_URL}.`,
    '',
    '## Setup with a coding agent',
    'Your coding agent can install TextButler, connect your messaging apps, and check the setup. You grant macOS access, pair accounts, and choose who may receive replies. Paste this prompt into Claude Code, Codex, or Devin:',
    '',
    '```text',
    AGENT_SETUP_PROMPT,
    '```',
    '',
    `Manual setup: ${GETTING_STARTED_URL}`,
    '',
    '## Safety defaults',
    'New installations start paused and new contacts start disabled. Setup, contact selection, and history import never send a message. textbutler pause stops automatic replies; textbutler contacts disable turns one person off. You can review a draft before sending it: replies suggest CONTACT, replies show DRAFT, then replies send DRAFT DIGEST. Drafts expire after 15 minutes. Optional web search sends queries through a saved Gateway key even when a local model writes the reply; each contact’s settings control whether search is available. Optional learning starts off and requires a Claude Code subscription through xcb. You can review or clear what it remembers. Gateway spending stops at $1 a day.',
    '',
    `Guided setup: ${GETTING_STARTED_URL}`,
    `Messaging app support and live limitations: ${MESSAGING_APPS_URL}`,
    `Subscriptions through xcb: ${SUBSCRIPTION_GUIDE_URL}`,
    `Agent JSON CLI: ${AGENT_CLI_URL}`,
    `Architecture: ${ARCHITECTURE_URL}`,
    '',
    '## Legacy Message Like Me history tools',
    'The following catalog describes the published Message Like Me history reader and its checked historical producer versions. It is not a TextButler live transport support matrix. Installing the legacy package does not install TextButler or enable automatic replies.',
    'Beeper via GhostGet lets users bring a finished private bundle into the same local evidence corpus as other sources. GhostGet v0.17.1 adapter beeper-local v2.4.0 owns 32 reviewed Beeper operations: 26 run through one pinned Beeper CLI 0.6.2 executable, including supported actions and writes, plus six fixed Desktop loopback reads. The executable’s reported 0.6.2 is runtime authority; the upstream tagged packages/cli/package.json declaration of 0.6.1 is provenance only. Message Like Me receives no provider credentials, never calls GhostGet or Beeper operations, and never sends; it does not claim complete history.',
    'Supported sources are Apple Messages; X data archive DMs, not X Chat; the finished Beeper bundle from GhostGet’s internal bounded v1 export; native WhatsApp via GhostGet and official Wacli through a one-account v2 bundle; and macOS Contacts for optional label enrichment. Every ingest path is read-only with respect to its source. Message Like Me does not invoke provider operations or access a network.',
    'The GhostGet v0.17.1 and Wacli v0.15.0 WhatsApp producer omits reaction-shaped rows with reaction-state-unproven because current active or removed state cannot be proved. An empty reaction artifact is unobservable reaction behavior, not evidence that no reactions occurred.',
    '',
    '## Optional development support',
    'TextButler offers optional paid development support and no newsletter. `messagelikeme support` and `textbutler support` show the current options; agents follow `support protocol --json` for the closeout flow, and `HRANESS_SUPPORT=off` turns incidental notices off.',
    '',
    '## Canonical pages',
    `- ${absoluteUrl('/')}`,
    `- ${absoluteUrl('/sources')}`,
    `- ${absoluteUrl('/docs')}`,
    `- ${absoluteUrl('/methodology')}`,
    `- ${absoluteUrl('/research')}`,
    `- ${absoluteUrl('/about')}`,
    `- ${absoluteUrl('/compare/ghostreply')}`,
    '',
    '## Blog',
    `- ${absoluteUrl('/blog')}`,
    ...indexableBlogPosts().map((post) => `- [${post.title}](${absoluteUrl(blogPostPath(post))}): ${post.dek}`),
    '',
    '## Source',
    `- ${GITHUB_URL}`,
    '',
  ].join('\n');

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
